command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

auth:
  - user

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "796f36d00b204fb6"
  - name: GENIE_SPACE_ID
    value: "01f0b40597a9152c935ddb6a25d08f59"

resources:
  - name: sql_warehouse
    sql_warehouse:
      id: 796f36d00b204fb6
      permission: CAN_USE
  - name: genie_space
    genie_space:
      id: 01f0b40597a9152c935ddb6a25d08f59
      permission: CAN_MANAGE
