command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

auth:
  - user

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "08381690ac2b0e1a"
  - name: GENIE_SPACE_ID
    value: "01f128afd07410268461ef36a3a865dd"

resources:
  - name: sql_warehouse
    sql_warehouse:
      id: 08381690ac2b0e1a
      permission: CAN_USE
  - name: genie_space
    genie_space:
      id: 01f128afd07410268461ef36a3a865dd
      permission: CAN_MANAGE
