command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

auth:
  - user

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "a1119b437a4a8d45"
  - name: GENIE_SPACE_ID
    value: "01f12fb14eb21d5e9864032b2d13316f"

resources:
  - name: valentina_warehouse
    sql_warehouse:
      id: a1119b437a4a8d45
      permission: CAN_USE
  - name: valentina_genie_space
    genie_space:
      id: 01f12fb14eb21d5e9864032b2d13316f
      permission: CAN_MANAGE
