command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

auth:
  - user

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "95381a6c659a6cfe"
  - name: GENIE_SPACE_ID
    value: "01f12fb6b13e17178757fe23739e1121"

resources:
  - name: valentina_warehouse
    sql_warehouse:
      id: 95381a6c659a6cfe
      permission: CAN_USE
  - name: valentina_genie_space
    genie_space:
      id: 01f12fb6b13e17178757fe23739e1121
      permission: CAN_MANAGE
